name: formfield
description: "Helper package to create common form fields needed in most apps."
version: 0.0.1
homepage: https://pwa.ir
repository: https://github.com/xclud/flutter-forms

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
